apps/recipes/config/routes.rb
Rails.application.routes.draw do
  resources :recipes do 
    resources :ingredients
  end
  get 'recipes/index'

  devise_for :users
devise_scope :user do
  authenticated :user do
    root :to => 'recipes#index', as: :authenticated_root
  end
  unauthenticated :user do
    root :to => 'devise/sessions#new', as: :unauthenticated_root
  end
end

end

apps/recipes/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

apps/recipes/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients, dependent: :destroy
	validates :name, presence: true
end

apps/recipes/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

apps/recipes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

apps/recipes/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def create
		@recipe = Recipe.find(params[:recipe_id])
		@ingredient = @recipe.ingredients.create(ingredient_params)
		redirect_to recipe_path(@recipe)
	end

	def destroy
		@recipe = Recipe.find(params[:recipe_id])
		@ingredient = @recipe.ingredients.find(params[:id])
		@ingredient.destroy
		redirect_to recipe_path(@recipe)
	end

	private
		def ingredient_params
			params.require(:ingredient).permit(:name, :quantity)
		end


end

apps/recipes/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all 
	end

	def new
		@recipe = Recipe.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			redirect_to @recipe
		else
			render 'edit'
		end
	end

	def create

		#render plain: params[:recipe].inspect
		# @recipe = Recipe.new(params[:recipe])
		@recipe = Recipe.new(recipe_params)
		
		if @recipe.save
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def show
		#how is the id created? Rails Magic?
		@recipe = Recipe.find(params[:id])
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy

		redirect_to recipes_path
	end

	private 
		def recipe_params
			params.require(:recipe).permit(:name, :description, :instructions)
		end	

end

apps/recipes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

apps/recipes/app/helpers/ingredients_helper.rb
module IngredientsHelper
end

apps/recipes/app/helpers/recipes_helper.rb
module RecipesHelper
end

apps/recipes/app/helpers/users_helper.rb
module UsersHelper
end

apps/recipes/app/helpers/welcome_helper.rb
module WelcomeHelper
end

apps/recipes/app/views/ingredients/_form.html.erb
<%= form_for ([@recipe, @recipe.ingredients.build]) do |f| %>
<p> 
	<%= f.label :quantity %>
</p>
<p>
	<%= f.text_area :quantity %>
</p>

<p>
	<%= f.label :name %>
</p>
<p>
	<%= f.text_field :name %>
</p>



<p>
<%= f.submit %>
</p>

<% end %>

apps/recipes/app/views/ingredients/_ingredient.html.erb
<p> 
	<%= ingredient.quantity %>
	<%= ingredient.name %>
	<%= link_to "Remove", [ingredient.recipe, ingredient], method: :delete, data: {confirm: "Are you sure you want to delete this deliciousness?"} %>
</p>

apps/recipes/app/views/recipes/_form.html.erb
<%= form_for :recipe, url: recipes_path do |f| %>

<!-- had trouble adding the error message here -->
 <div class = "new">
 <link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description%>
	</p>

	<p>
		<%= f.label :instructions %><br>
		<%= f.text_area :instructions%>
	</p>


	<p>
		<%= f.submit %>
	</p>

<% end %>

</div>

apps/recipes/app/views/recipes/edit.html.erb
<div class = "recipe">
	<link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
<h1>Edit Your Recipe</h1>

<%= form_for :recipe, url: recipe_path(@recipe), method: :patch do |f| %>

<p>
<%= f.label :name %>
</p>
<p>
<%= f.text_field :name %>
</p>

<p>
	<%= f.label :description %>
</p>
<p>
	<%= f.text_area :description %>
</p>

<p>
	<%= f.label :instructions %>
</p>
<p>
	<%= f.text_area :instructions %>
</p>

<%= f.submit %>
<% end %>
<br><br>
<!-- go back to recipe that has been worked on (not recipes_path)-->
<%= link_to "Back To Recipe", recipe_path(@recipe) %>
</div>

apps/recipes/app/views/recipes/index.html.erb
<h1>Recipes for the Bru</h1>
<!-- Single button -->
<link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>

 <div>
  <button type="button" class="btn btn-fairy btn-lg">
    <%= link_to "New Recipe", new_recipe_path %>
  </button>
</div>

<h2> Here is a list of all of your recipes!</h2>

<table>
  <tr>
    <th>What would you like to cook today?</th>
  </tr>

  <div class = "list">
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
  <% @recipes.each do |recipe| %>
    <tr>
     <td><br><%= link_to "#{recipe.name}", recipe_path(recipe) %><br><br></td>
     </td>
    </tr>
  <% end %>
</div>

</table>

apps/recipes/app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

	<%= link_to "Back to All Recipes", recipes_path %>

	

apps/recipes/app/views/recipes/show.html.erb
<div class = "recipe">
	<link href='http://fonts.googleapis.com/css?family=Oswald:700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>
<div id="wrapper">

<!-- #simple toggle menu done fucked me up -->

<p>
	<strong>Recipe Name:</strong>
</p>
<div class = "description">
	<p>
		<%= @recipe.name %>
	</p>
</div>
<br>

<p>
	<strong>Description:</strong>
</p>
<div class = "description">
	<p>
		<%= @recipe.description %>
	</p>
</div>
<br>
<p>
	<strong>Instructions:</strong>
</p>
<div class = "description">
	<p>
		<%= @recipe.instructions %>
	</p>
</div>

<!-- <div class = "header">
	<h2> -->
<br>
		<strong>Ingredients:</strong>
	</h2>
<!-- </div> -->
<%= render @recipe.ingredients %>


<strong>
	<h2> Add an Ingredient: </h2>
</strong>
<%= render 'ingredients/form' %>

<!-- link_to Back to All Recipes, Edit Recipe, Delete Recipe
 -->
 <%= link_to "Back to All Recipes", recipes_path %><br><br>
<%= link_to "Edit Recipe", edit_recipe_path(@recipe) %><br><br>
<%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure you want to delete this deliciousness?"} %> 
</div>